language: java
script: mvn test -B
jdk: oraclejdk8

cache:
  directories:
    - $HOME/.m2

notifications:
  slack:
    on_success: always
    on_failure: always
    rooms:
      - secure: "fpjmU17J1b6Fv4w0D+qaWguxowwekbCMdxOTf4TuS9jxnzWegy7Y08eIlim40B3VGkkFJ8tPpKskgEUweD9xnRukA13+JIv4INjlZJPMw4H5SOyrbvBWbHzg/nSdP3yqje18CFwTc+m0vbTxwV1gab5XRcR/H+tNBBV9JhLotdvOztWbQo2tq5nXWs5/YuYHVHFC9NSjD++69L4f0sq3zR4RngZPOcbs0AFwWLeZlDfiXuVN+GiytAH0JPDQJDU8lvAQkKs4pr7GWLpatHkfmAwx9RVQIBGxbrZxEm+ik4J+eSIPATvgAdkziL8Rs19qJCCt0H0mWb7QhtnFf83MfagjS8zG+BN35hJ0TWv2BBgg1dzeJN5A56DpexvaeU86EEibP9RrkiteCHRyoxYizk25qt0Md6JvR6PVUjGe1IyiXpBNGQjxuz5CKRn3jXd/oWspJpI26BJkhpdPHyPlO++6QNqLkUmmnUHfE35Qq6PeikJSqGP320/4Qn/ltjags47XsYNoQvT0fEVXjKjWjdVeWCa/MNlYAGvdq0qS10Ta8Y8WWx5xhucoukfxk43FMBbELHc11ucrdJ0cokhJItxdbkhUef+vnXNlCM+h5aQwUxDhWWYqw6fIUcfrMWkchxsW0qcXwGIM8My/XZe256oi1whNN4dd2M+0KNvUjzs="

    
